version: "3.8"
services:
  dentaltec-app:
    image: ${APP_NAME}-dentaltec
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-dentaltec.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-dentaltec.tls.certresolver=myresolver"
      - "traefik.http.routers.${APP_NAME}-dentaltec.service=service-${APP_NAME}-dentaltec"

      - "traefik.http.services.service-${APP_NAME}-dentaltec.loadbalancer.server.port=3000"

networks:
  traefik-net:
    external: true
